#ifndef ST19AFT_DEFINES_H_
#define ST19AFT_DEFINES_H_

/* Channel numbers for bcodes */
#define CH_JOY					1
#define CH_TRAJ 				2
#define CH_TARG 				3
#define CH_BLIP_OMEGA_MAX 		4
#define CH_BLIP_DURATION_FRAMES	5
#define CH_JUMP_SIZE			6
#define CH_JUMP_ACTUAL			7

#define CH_FRAMES_PER_SECOND		100
#define CH_SPEED 					101
#define CH_MS_BEFORE_JUMP			102
#define CH_MS_AFTER_JUMP			103
#define CH_NTRIALS					104
#define CH_JUMPS_PER_TRIAL			105
#define CH_STEER_MAX_DEGREES		106
#define CH_TARG_OFFSET_DEGREES_0	107
#define CH_TARG_OFFSET_DEGREES_1	108
#define CH_BLINK_PROBABILITY_PER_JUMP	109
#define CH_BLINK_DURATION_MS		110
#define CH_BLINK_GUARD_MS			111
#define CH_BLIP_PROBABILITY_PER_JUMP	112
#define CH_BLIP_DURATION_MS			113
#define CH_BLIP_GUARD_MS			114
#define CH_BLIP_MAX_ANG_VELOCITY_DEG_PER_SEC	115
#define CH_TARG_OFFSET_DEGREES_2	116
#define CH_TARG_OFFSET_DEGREES_3	117
#define	CH_STEER_ZERO				119
#define CH_STEER_DEAD				120
#define CH_REWARD_WINDOW_DEGREES	121
#define CH_SCREEN_DISTANCE_MM		122
#define CH_FAR_PLANE_DISTANCE		123
#define CH_CAMERA_HEIGHT			124
#define CH_TARGET_DIAM_DEGREES		125
#define CH_TARG_COLOR_R				126
#define CH_TARG_COLOR_G				127
#define CH_TARG_COLOR_B				128
#define CH_TARG_DIST				129
#define	CH_TARG_HEIGHT_DEGREES		130
#define CH_GP_LENGTH				131
#define CH_GP_WIDTH					132
#define CH_DOTS_PER_GRID			133
#define CH_GRID_POOL_SIZE			134
#define CH_PLANE_R					135
#define CH_PLANE_G					136
#define CH_PLANE_B					137
#define CH_DOT_R					138
#define CH_DOT_G					139
#define CH_DOT_B					140
#define CH_GRID_FLAGS				141
#define CH_DOT_SIZE					142
#define CH_BACKGROUND_R				143
#define CH_BACKGROUND_G				144
#define CH_BACKGROUND_B				145
#define CH_BLINK_RATE				146
#define CH_BLINK_MS					147
#define CH_BLINK_DEBUG				149
#define CH_BLIP_RATE				150
#define CH_BLIP_MS					151
#define CH_BLIP_MAX_VEL				153
#define CH_BLIP_DEBUG				154
#define CH_REW_ACQUISITION_MS		155
#define CH_REW_WAIT_MAX				156
#define CH_REW_WAIT_MIN				157
#define CH_REW_RAMP					158
#define CH_TARG_OFFSET_DEGREES_4	159
#define CH_TARG_OFFSET_DEGREES_5	160
#define CH_TARG_OFFSET_DEGREES_6	161
#define CH_TARG_OFFSET_DEGREES_7	162
#define CH_TARG_OFFSET_DEGREES_8	163
#define CH_TARG_OFFSET_DEGREES_9	164
#define CH_TARG_OFFSET_WEIGHT_0		165
#define CH_TARG_OFFSET_WEIGHT_1		166
#define CH_TARG_OFFSET_WEIGHT_2		167
#define CH_TARG_OFFSET_WEIGHT_3		168
#define CH_TARG_OFFSET_WEIGHT_4		169
#define CH_TARG_OFFSET_WEIGHT_5		170
#define CH_TARG_OFFSET_WEIGHT_6		171
#define CH_TARG_OFFSET_WEIGHT_7		172
#define CH_TARG_OFFSET_WEIGHT_8		173
#define CH_TARG_OFFSET_WEIGHT_9		174
#define CH_FIXPT_X					180
#define CH_FIXPT_Y					181
#define CH_FIXPT_DIAMETER			182
#define CH_FIXPT_WINDOW				183
#define CH_FIXPT_ACQTIME			184
#define CH_FIXPT_ACQTIMEOUT			185
#define CH_FIXPT_FIXTIME			186
#define CH_FIXPT_FIXTIMEOUT			187
#define CH_FIXPT_R					188
#define CH_FIXPT_G					189
#define CH_FIXPT_B					190


/* Eye window stuff */
#define WIND0	    0


#endif /*ST19AFT_DEFINES_H_*/
